name: hiddify
description: Cross Platform Multi Protocol Proxy Frontend.
publish_to: "none"
version: 3.0.0+30000

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: "^3.29.3"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # cupertino_icons: ^1.0.6
  intl: ^0.19.0
  # humanizer: ^2.2.0
  # intl: ^0.19.0
  humanizer:
    git:
      url: https://github.com/alex-relov/humanizer
      ref: up-version
  # lucy_editor: ^1.0.5
  # re_highlight: ^0.0.3
  # json_editor_flutter: ^1.4.2

  slang: ^4.4.0
  slang_flutter: ^4.4.0
  fpdart: ^1.1.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  hooks_riverpod: ^2.4.10
  flutter_hooks: ^0.20.5
  riverpod_annotation: ^2.3.4
  rxdart: ^0.28.0
  drift: ^2.21.0
  drift_flutter: ^0.2.1
  shared_preferences: ^2.5.2
  # shared_preferences_android: ^2.4.8
  dio: ^5.4.1
  ffi: ^2.1.2
  path_provider: ^2.1.1
  mobile_scanner: ^6.0.1
  # protocol_handler: ^0.2.0
  flutter_native_splash: ^2.3.10
  share_plus: ^10.1.0
  window_manager: ^0.4.2
  tray_manager: ^0.4.0

  package_info_plus: ^8.1.0

  url_launcher: ^6.2.5
  vclibs: ^0.1.2
  launch_at_startup: ^0.5.1
  sentry_flutter: ^8.14.0
  sentry_dart_plugin: ^2.4.1
  sqlite3_flutter_libs: ^0.5.28

  combine: ^0.5.7
  path: ^1.9.0
  loggy: ^2.0.3
  flutter_loggy: ^2.0.2
  meta: ^1.15.0
  dartx: ^1.2.0
  uuid: ^4.3.3
  tint: ^2.0.1
  accessibility_tools: ^2.2.3
  neat_periodic_task: ^2.0.1
  watcher: ^1.1.0
  go_router: ^14.3.0
  flutter_animate: ^4.5.0
  flutter_svg: ^2.0.10+1
  gap: ^3.0.1
  # percent_indicator_premium: ^0.0.2
  sliver_tools: ^0.2.12
  flutter_adaptive_scaffold: ^0.3.1
  font_awesome_flutter: ^10.7.0
  upgrader: ^11.3.0
  toastification: ^2.3.0
  version: ^3.0.2
  posix: ^6.0.1
  qr_flutter: ^4.1.0
  flutter_displaymode: ^0.6.0
  flutter_loggy_dio: ^3.1.0
  dio_smart_retry: ^7.0.1
  cupertino_http: ^2.0.1
  dart_mappable: ^4.2.1
  fluentui_system_icons: ^1.1.229
  timezone_to_country: ^3.0.0
  json_path: ^0.7.1
  # permission_handler: ^11.3.0 # is not compatible with windows
  #flutter_easy_permission: ^1.1.2
  # flutter_easy_permission:
  #   git: https://github.com/MichaelStH/flutter_easy_permission.git
  in_app_review: ^2.0.10
  # circle_flags: ^4.0.2
  circle_flags:
    git: https://github.com/hiddify-com/flutter_circle_flags.git
  fixnum: ^1.1.0
  grpc: ^4.0.1
  bottom_navy_bar: ^6.1.0
  # # for using protobuf install protoc from this link -> https://github.com/protocolbuffers/protobuf/releases
  # # then add path to "environment variable" e.g. -> C:\src\protoc-28.3-win64\bin
  # # then active "protoc_plugin" by running this command -> dart pub global activate protoc_plugin
  # # then add path to "environment variable" e.g. -> C:\Users\%USERPROFILE%\AppData\Local\Pub\Cache\global_packages\protoc_plugin\bin
  protobuf: ^2.0.0
  dynamic_color: ^1.7.0
  flutter_typeahead: ^5.0.1
  # flutter_platform_widgets: ^7.0.1
  simple_icons: ^10.1.3
  animated_notch_bottom_bar: ^1.0.0
  basic_utils: 5.7.0
  showcaseview: 3.0.0
  text_scroll: ^0.2.0
  flutter_markdown: ^0.7.6+2
  # platform-specific  settings
  # https://github.com/miguelpruivo/flutter_file_picker/wiki/Setup
  file_picker: ^8.1.7
  installed_apps: # ^1.5.2
    git: https://github.com/VB10/installed_apps

  # change case of text
  # for example camelCase to snake_case
  # helloWorld -> hello_worlds
  recase: ^4.1.0
  # Used for managing deep links on desktop platforms
  # platform-specific settings
  # https://github.com/llfbandit/app_links/tree/master/doc
  app_links: ^6.4.0
  # Used for registering custom schemes in the Windows registry
  win32: ^5.12.0

dev_dependencies:
  # flutter_test:
  #   sdk: flutter
  lint: ^2.3.0
  build_web_compilers: ^4.0.11
  protoc_plugin: ^20.0.1
  build_runner: ^2.4.13
  json_serializable: ^6.7.1
  freezed: ^2.4.7
  riverpod_generator: ^2.4.3
  drift_dev: ^2.21.0
  ffigen: ^16.0.0
  slang_build_runner: ^4.4.0
  flutter_gen_runner: ^5.4.0
  go_router_builder: ^2.4.1
  dependency_validator: ^4.1.1
  dart_mappable_builder: ^4.2.1
  # protoc_builder: ^0.4.1
  # google_protobuf: ^3.20.1;

flutter:
  uses-material-design: true
  assets:
    # - assets/core/geoip.db
    # - assets/core/geosite.db
    - assets/images/logo.svg
    - assets/images/tray_icon.ico
    - assets/images/tray_icon.png
    - assets/images/tray_icon_dark.ico
    - assets/images/tray_icon_dark.png
    - assets/images/tray_icon_connected.ico
    - assets/images/tray_icon_connected.png
    - assets/images/tray_icon_disconnected.ico
    - assets/images/tray_icon_disconnected.png
    - assets/images/connect_norouz.PNG
    - assets/images/disconnect_norouz.PNG
    - assets/images/world_map.png

  fonts:
    - family: Shabnam
      fonts:
        - asset: assets/fonts/Shabnam.ttf
    # - family: Roboto
    #   fonts:
    #     - asset: assets/fonts/Roboto.ttf
    - family: Emoji
      fonts:
        - asset: assets/fonts/Emoji.ttf

flutter_gen:
  output: lib/gen/
  integrations:
    flutter_svg: true

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/source/ic_launcher_splash.png
  android_gravity: center
  android_12:
    color: "#ffffff"
    image: assets/images/source/ic_launcher_foreground.png

ffigen:
  name: "HiddifyCoreNativeLibrary"
  description: "Bindings to Hiddify Core Library"
  output: "lib/gen/hiddify_core_generated_bindings.dart"
  headers:
    entry-points:
      - "hiddify-core/bin/desktop.h"

sentry:
  upload_debug_symbols: true
  upload_source_maps: true
  upload_sources: true
  log_level: info
  ignore_missing: true
