name: hiddify
description: Cross Platform Multi Protocol Proxy Frontend.
publish_to: "none"
version: 2.5.7+20507

environment:
  sdk: ">=3.9.0 <4.0.0"
  flutter: ">=3.35.0 <4.0.0"

dependencies:
  accessibility_tools: ^2.7.1
  # circle_flags: ^4.0.2
  circle_flags:
    git:
      url: https://github.com/hiddify-com/flutter_circle_flags.git
  cupertino_icons: ^1.0.6
  dart_mappable: ^4.2.1
  dartx: ^1.2.0
  dio: ^5.4.1
  dio_smart_retry: ^7.0.1
  drift: ^2.16.0
  dynamic_color: ^1.7.0
  ffi: ^2.1.2
  fluentui_system_icons: ^1.1.229
  flutter:
    sdk: flutter
  flutter_adaptive_scaffold: ^0.3.3+1  # Discontinued (Feb 2025) - Migrate to Material 3 adaptive features or community fork
  flutter_animate: ^4.5.0
  flutter_displaymode: ^0.7.0
  flutter_hooks: ^0.21.3+1
  flutter_localizations:
    sdk: flutter
  flutter_loggy: ^2.0.2
  flutter_loggy_dio: ^3.0.1
  flutter_native_splash: ^2.4.6
  flutter_riverpod: ^3.0.2
  flutter_svg: ^2.0.10+1
  flutter_typeahead: ^5.0.1
  fpdart: ^1.1.0
  freezed_annotation: ^3.1.0
  gap: ^3.0.1
  go_router: ^16.2.4
  grpc: ^4.1.0
  hooks_riverpod: ^3.0.2
  http: ^1.2.0
  humanizer: ^3.0.1
  in_app_review: ^2.0.9
  intl: ^0.20.2
  json_annotation: ^4.9.0
  json_path: ^0.8.0
  launch_at_startup: ^0.3.1
  loggy: ^2.0.3
  meta: ^1.16.0  # Added to satisfy linter for direct imports
  mobile_scanner: ^7.1.2
  neat_periodic_task: ^2.0.1
  package_info_plus: ^9.0.0
  path: ^1.8.3
  path_provider: ^2.1.1
  percent_indicator: ^4.2.3
  permission_handler: ^12.0.1
  posix: ^6.0.1
  protobuf: ^4.2.0
  protocol_handler: ^0.2.0
  qr_flutter: ^4.1.0
  riverpod: ^3.0.2
  riverpod_annotation: ^3.0.2
  rxdart: ^0.28.0
  sentry_flutter: ^9.7.0
  share_plus: ^12.0.0
  shared_preferences: ^2.2.2
  slang: ^4.9.0
  slang_flutter: ^4.9.0
  sliver_tools: ^0.2.12
  sqlite3_flutter_libs: ^0.5.40
  state_notifier: ^1.0.0
  timezone_to_country: ^3.0.0
  tint: ^2.0.1
  toastification: ^3.0.3
  tray_manager: ^0.5.1
  upgrader: ^12.1.0
  url_launcher: ^6.2.5
  uuid: ^4.3.3
  vclibs: ^0.1.2
  vector_graphics: ^1.1.19
  version: ^3.0.2
  watcher: ^1.1.0
  win32: ^5.15.0
  window_manager: ^0.5.1
  wolt_modal_sheet: ^0.11.0
  # lucy_editor: ^1.0.5
  # re_highlight: ^0.0.3
  # json_editor_flutter: ^1.4.2
  # permission_handler: ^11.3.0 # is not compatible with windows
  # flutter_easy_permission: ^1.1.2

dev_dependencies:
  build_runner: ^2.7.1
  custom_lint: ^0.8.0  # Downgraded to resolve analyzer conflict with dependency_validator
  dart_mappable_builder: ^4.6.0  # Downgraded to resolve analyzer conflict with dependency_validator
  dependency_validator: ^5.0.2
  drift_dev: ^2.28.3
  ffigen: ^19.1.0
  flutter_gen_runner: ^5.12.0
  flutter_test:
    sdk: flutter
  freezed: ^3.2.3
  go_router_builder: ^4.1.0
  json_serializable: ^6.11.1
  lint: ^2.3.0
  riverpod_generator: ^3.0.2
  riverpod_lint: ^3.0.2
  sentry_dart_plugin: ^3.1.1
  slang_build_runner: ^4.9.0

dependency_overrides:
  # drift & package_info_plus are not compatible
  web: ^1.1.1

flutter:
  uses-material-design: true
  assets:
    # - assets/core/geoip.db
    # - assets/core/geosite.db
    - assets/images/logo.svg
    - assets/images/tray_icon.ico
    - assets/images/tray_icon.png
    - assets/images/tray_icon_dark.ico
    - assets/images/tray_icon_dark.png
    - assets/images/tray_icon_connected.ico
    - assets/images/tray_icon_connected.png
    - assets/images/tray_icon_disconnected.ico
    - assets/images/tray_icon_disconnected.png
    - assets/images/connect_norouz.PNG
    - assets/images/disconnect_norouz.PNG

  fonts:
    - family: Shabnam
      fonts:
        - asset: assets/fonts/Shabnam.ttf
    # - family: Roboto
    #   fonts:
    #     - asset: assets/fonts/Roboto.ttf
    - family: Emoji
      fonts:
        - asset: assets/fonts/Emoji.ttf

flutter_gen:
  output: lib/gen/
  integrations:
    flutter_svg: true

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/source/ic_launcher_splash.png
  android_gravity: center
  android_12:
    color: "#ffffff"
    image: assets/images/source/ic_launcher_foreground.png

ffigen:
  name: "SingboxNativeLibrary"
  description: "Bindings to Singbox"
  output: "lib/gen/singbox_generated_bindings.dart"
  headers:
    entry-points:
      - "libcore/bin/libcore.h"
  llvm-path:
    - "C:/Program Files/LLVM/bin"

sentry:
  upload_debug_symbols: true
  upload_source_maps: true
  upload_sources: true

